/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"fmt"
	"reflect"

	"go.universe.tf/metallb/api/v1beta1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/predicate"

	nbv1 "code.swisscom.com/swisscom/mobile/kubernetes-operators/netbox-operator.git/api/v1"
	hydrationdemov1alpha1 "code.swisscom.com/swisscom/mobile/playground/nike/config-hydration-examples/api/v1alpha1"
)

// ConfigurationReconciler reconciles a Configuration object
type ConfigurationReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=hydration-demo.swisscom.com,resources=configurations,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=hydration-demo.swisscom.com,resources=configurations/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=hydration-demo.swisscom.com,resources=configurations/finalizers,verbs=update
// +kubebuilder:rbac:groups=netbox.dev,resources=prefixclaims,verbs=get;list;watch
// +kubebuilder:rbac:groups=netbox.dev,resources=prefixclaims/status,verbs=get
// +kubebuilder:rbac:groups=metallb.io,resources=ipaddresspools,verbs=get;list;watch

// Reconcile is part of the main kubernetes reconciliation loop which aims to
// move the current state of the cluster closer to the desired state.
// TODO(user): Modify the Reconcile function to compare the state specified by
// the Configuration object against the actual cluster state, and then
// perform operations to make the cluster state reflect the state specified by
// the user.
//
// For more details, check Reconcile and its Result here:
// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.18.4/pkg/reconcile
func (r *ConfigurationReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	// Configuration logic
	o := &hydrationdemov1alpha1.Configuration{}
	if err := r.Get(ctx, req.NamespacedName, o); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	intermediate := &nbv1.PrefixClaim{
		ObjectMeta: metav1.ObjectMeta{
			Name:      req.Name,
			Namespace: req.Namespace,
		},
	}

	_, err := ctrl.CreateOrUpdate(ctx, r.Client, intermediate, func() error {
		intermediate.Spec = nbv1.PrefixClaimSpec{
			ParentPrefix:     o.Spec.ParentPrefix,
			PrefixLength:     o.Spec.PrefixLength,
			PreserveInNetbox: true,
			Description:      "Automatically generated by Operator",
		}
		err := controllerutil.SetOwnerReference(o, intermediate, r.Scheme)
		if err != nil {
			return err
		}
		logger.Info("ownerReference set", "ownerReference namespace", o.Namespace, "ownerReference name", o.Name)
		return nil
	})
	if err != nil {
		return ctrl.Result{}, err
	}
	logger.Info("intermediate created", "parentPrefix", intermediate.Spec.ParentPrefix, "prefixLength", intermediate.Spec.PrefixLength)

	// PrefixClaim logic
	if !meta.IsStatusConditionTrue(intermediate.Status.Conditions, nbv1.ConditionPrefixClaimReadyTrue.Type) {
		return ctrl.Result{}, fmt.Errorf("prefix claim '%s' is not ready", req.NamespacedName.String())
	}
	logger.Info("intermediate is ready", "Prefix", intermediate.Status.Prefix)

	// We only care about PrefixClaims that are owned by a Configuration
	if len(intermediate.ObjectMeta.OwnerReferences) == 0 || intermediate.ObjectMeta.OwnerReferences[0].Kind != "Configuration" {
		return ctrl.Result{}, nil
	}

	final := &v1beta1.IPAddressPool{
		ObjectMeta: metav1.ObjectMeta{
			Name:      req.Name,
			Namespace: "metallb-system", // forced by admission webhook
		},
	}

	_, err = ctrl.CreateOrUpdate(ctx, r.Client, final, func() error {
		final.Spec.Addresses = []string{intermediate.Status.Prefix}
		err := controllerutil.SetOwnerReference(o, final, r.Scheme)
		if err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return ctrl.Result{}, err
	}
	logger.Info("MetalLB IPAddressPool created", "Addresses", final.Spec.Addresses)

	meta.SetStatusCondition(&o.Status.Conditions, hydrationdemov1alpha1.ConditionReadyTrue)
	err = r.Client.Status().Update(ctx, o)
	if err != nil {
		return ctrl.Result{}, err
	}

	return ctrl.Result{}, nil
}

// SetupWithManager sets up the controller with the Manager.
func (r *ConfigurationReconciler) SetupWithManager(mgr ctrl.Manager) error {
	p := predicate.Funcs{
		UpdateFunc: func(e event.UpdateEvent) bool {
			oldObject := e.ObjectOld.(*nbv1.PrefixClaim)
			newObject := e.ObjectNew.(*nbv1.PrefixClaim)

			return !reflect.DeepEqual(oldObject.Status, newObject.Status)
		},
	}
	return ctrl.NewControllerManagedBy(mgr).
		For(&hydrationdemov1alpha1.Configuration{}).
		Owns(&nbv1.PrefixClaim{}).
		Watches(&nbv1.PrefixClaim{}, &handler.EnqueueRequestForObject{}, builder.WithPredicates(p)).
		Owns(&v1beta1.IPAddressPool{}).
		Complete(r)
}
