---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kform-prefix-to-ipclaim-template
  namespace: default
  annotations:
    kform.dev/block-type: input
    kform.dev/resource-id: context
    kform.dev/default: "true"
  labels:
    demo: input
data:
  parentPrefix: "10.0.0.0/16"
  prefixLength: "/24"
