---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hydration-demo.swisscom.com
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hydration-demo.swisscom.com
  resources:
  - configurations/finalizers
  verbs:
  - update
- apiGroups:
  - hydration-demo.swisscom.com
  resources:
  - configurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metallb.io
  resources:
  - ipaddresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbox.dev
  resources:
  - prefixclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbox.dev
  resources:
  - prefixclaims/status
  verbs:
  - get
